// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQSsBYoY6YZbyGAyv1LRuQmiVL1_711FA',
    appId: '1:547833466237:web:5870c94353ffb9ca6d1014',
    messagingSenderId: '547833466237',
    projectId: 'kinder-1b8f0',
    authDomain: 'kinder-1b8f0.firebaseapp.com',
    storageBucket: 'kinder-1b8f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ydyB_0ZiWPhm9rXbKf7IT5OeWddlNYI',
    appId: '1:547833466237:android:d449bf9a438682976d1014',
    messagingSenderId: '547833466237',
    projectId: 'kinder-1b8f0',
    storageBucket: 'kinder-1b8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqTocT0D0aTDKDP4mzzhxB4rpetPXPPk',
    appId: '1:547833466237:ios:20107939c3cd59b56d1014',
    messagingSenderId: '547833466237',
    projectId: 'kinder-1b8f0',
    storageBucket: 'kinder-1b8f0.firebasestorage.app',
    iosClientId: '547833466237-shghmnb7lj7ko7hn17b565rucdorrgab.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQSsBYoY6YZbyGAyv1LRuQmiVL1_711FA',
    appId: '1:547833466237:web:96381f4da56d58866d1014',
    messagingSenderId: '547833466237',
    projectId: 'kinder-1b8f0',
    authDomain: 'kinder-1b8f0.firebaseapp.com',
    storageBucket: 'kinder-1b8f0.firebasestorage.app',
  );
}
